const projects = [
  { number: '01', title: 'Energy Crisis: analysis & insights', type: 'Research / analysis', description: 'An analysis of a February 2026 energy supply shock, with demand and supply dynamics, price impact and a market outlook using IEA data.', tags: ['Energy markets', 'Data analysis', 'Storytelling'], href: 'https://drive.google.com/file/d/146ujz5MjqL88xoaF8321JfPwDYlg4mdg/view?usp=drive_link', action: 'View analysis', visual: 'energy' },
  { number: '02', title: 'Customer churn intelligence', type: 'Dashboard / reporting', description: 'An interactive Looker Studio report examining churn patterns and the drivers behind customer retention.', tags: ['Looker Studio', 'Customer analytics', 'BI'], href: 'https://datastudio.google.com/reporting/64456cc1-ea3a-49bd-b533-74156a9ad61e', action: 'Open dashboard', visual: 'churn' },
];

function DataVisual({ kind }: { kind: string }) {
  return <div className={`project-visual ${kind}`} aria-hidden="true">
    <div className="visual-top"><span>ANALYSIS / {kind === 'energy' ? '01' : '02'}</span><span>● ● ●</span></div>
    <svg viewBox="0 0 520 240" preserveAspectRatio="none">
      <g className="grid-lines"><path d="M0 40H520M0 88H520M0 136H520M0 184H520M85 0V240M172 0V240M259 0V240M346 0V240M433 0V240" /></g>
      {kind === 'energy' ? <><path className="line-muted" d="M0 172C50 150 73 165 110 145S180 160 222 125 290 146 328 103 390 115 430 82 487 96 520 62"/><path className="line-main" d="M0 190C44 186 74 195 112 176S178 183 221 155 278 166 325 129 384 132 430 76 482 89 520 29"/><circle cx="430" cy="76" r="6" fill="#8df0e3"/></> : <><path className="line-muted" d="M0 55C66 60 78 91 130 85S202 112 260 106 343 141 390 133 465 166 520 161"/><path className="line-main" d="M0 192C52 177 86 188 130 159S203 170 260 132 326 148 390 105 466 117 520 66"/><circle cx="390" cy="105" r="6" fill="#8df0e3"/></>}
    </svg>
    <div className="visual-bottom"><span>01 / INPUT</span><span>02 / MODEL</span><span>03 / INSIGHT</span></div>
  </div>;
}

function PipelineVisual() {
  return <div className="pipeline" aria-label="Planned platform flow: sources to ingestion to modeling to insight">
    {['SOURCES', 'INGESTION', 'MODELING', 'INSIGHT'].map((stage, i) => <div className="pipeline-step" key={stage}><span className="pipeline-index">0{i + 1}</span><strong>{stage}</strong>{i < 3 && <span className="connector" aria-hidden="true"/>}</div>)}
  </div>;
}

export default function Home() {
  return <>
    <header className="site-header"><a className="brand" href="#top" aria-label="Meena Raja, back to top"><span className="brand-mark">M<span>.</span></span><span>MEENA RAJA</span></a><nav aria-label="Main navigation"><a href="#about">About</a><a href="#work">Work</a><a href="#experience">Experience</a><a href="#contact">Contact</a></nav><a className="nav-contact" href="https://www.linkedin.com/in/meenar09" target="_blank" rel="noopener noreferrer">Connect <span aria-hidden="true">↗</span></a></header>
    <main id="top">
      <section className="hero wrap" aria-labelledby="hero-title"><div className="hero-main"><div className="eyebrow"><span className="eyebrow-line"/> DATA · ANALYTICS · ENGINEERING</div><h1 id="hero-title">Making data<br/><em>make sense.</em></h1><p className="hero-copy">I’m Meena Raja. I turn complex data into reliable reporting, clear insights and better decisions — with six years of experience across analytics and operations.</p><div className="hero-actions"><a className="button button-primary" href="#work">Explore my work <span aria-hidden="true">↗</span></a><a className="button button-quiet" href="https://drive.google.com/file/d/1aHG-IV6eEDR23dvArWh8IgxKbK-CsIUa/view?usp=drive_link" target="_blank" rel="noopener noreferrer">View résumé <span aria-hidden="true">↗</span></a></div></div><div className="hero-side" aria-label="From raw data to useful decisions"><div className="orbit"><div className="orbit-core">DATA<br/><span>→ VALUE</span></div><span className="orb orb-a"/><span className="orb orb-b"/><span className="orb orb-c"/></div><div className="hero-caption"><span>01 / 03</span><span>CONNECTING THE DOTS<br/>BETWEEN DATA AND ACTION</span></div></div><div className="hero-bottom"><span>BASED IN GERMANY · WORKING ACROSS DISCIPLINES</span><span>SCROLL TO EXPLORE ↓</span></div></section>
      <section className="metrics"><div className="wrap metrics-inner"><div><strong>6<span>+</span></strong><span>years in analytics & reporting</span></div><div><strong>100<span>+</span></strong><span>reports built and automated</span></div><div><strong>80<span>%</span></strong><span>less manual processing in a reporting workflow</span></div></div></section>
      <section className="section wrap about-section" id="about"><div className="section-kicker">01 / ABOUT</div><div className="about-layout"><h2>Curiosity meets<br/><em>precision.</em></h2><div><p className="lead">I work at the intersection of data, business needs and the people making decisions.</p><p>Across Rocket India and HDFC Bank, I’ve built reporting for multiple teams, improved data validation and automated recurring workflows. I’m now extending that experience into data engineering and end-to-end platforms.</p><div className="skill-list" aria-label="Skills"><span>SQL</span><span>Power BI</span><span>Python</span><span>Excel</span><span>ETL</span><span>Data modeling</span><span>Power Automate</span></div></div></div></section>
      <section className="section work-section" id="work"><div className="wrap"><div className="section-heading"><div><div className="section-kicker">02 / SELECTED WORK</div><h2>Work that<br/><em>moves things forward.</em></h2></div><p>From analysis to dashboards and the data systems behind them.</p></div><div className="project-grid">{projects.map(project => <article className="project-card" key={project.number}><DataVisual kind={project.visual}/><div className="project-body"><div className="project-meta"><span>{project.number} / {project.type}</span><span>↗</span></div><h3>{project.title}</h3><p>{project.description}</p><div className="tags">{project.tags.map(tag => <span key={tag}>{tag}</span>)}</div><a href={project.href} target="_blank" rel="noopener noreferrer" className="text-link">{project.action} <span aria-hidden="true">↗</span></a></div></article>)}</div><article className="future-project"><div><div className="section-kicker">IN DEVELOPMENT / 03</div><h3>German freight bottleneck & delay platform</h3><p>An upcoming portfolio project exploring freight delays and logistics bottlenecks in Germany. Planned stack: Python, Apache Airflow, dbt, SQL and data modeling. Architecture and results will be added as the work progresses.</p></div><PipelineVisual/></article></div></section>
      <section className="section wrap experience-section" id="experience"><div className="section-kicker">03 / EXPERIENCE</div><div className="experience-layout"><div><h2>Built in<br/><em>the real world.</em></h2><p>Reliable data work is as much about collaboration and context as it is about technical execution.</p><a className="text-link" href="https://github.com/Meenar-9196/Data-Reporting-Projects-Meena" target="_blank" rel="noopener noreferrer">Explore my GitHub <span aria-hidden="true">↗</span></a></div><div className="timeline"><div className="timeline-item"><span>2022 — 2026</span><div><h3>Data and Reporting Analyst II</h3><p>Rocket India</p><small>Reporting, automation, data quality and cross-functional analytics.</small></div></div><div className="timeline-item"><span>2020 — 2022</span><div><h3>Deputy Manager — Data Analyst</h3><p>HDFC Bank Ltd</p><small>Data analysis and reporting for business operations.</small></div></div><div className="timeline-item"><span>2018 — 2020</span><div><h3>MBA, Banking Technology</h3><p>Pondicherry University</p></div></div></div></div></section>
      <section className="contact-section" id="contact"><div className="wrap contact-inner"><div className="section-kicker">04 / CONTACT</div><h2>Let’s make<br/><em>something useful.</em></h2><p>Open to conversations about data roles, analytics projects and collaboration.</p><div className="contact-actions"><a href="https://www.linkedin.com/in/meenar09" target="_blank" rel="noopener noreferrer" className="button button-primary">Connect on LinkedIn <span aria-hidden="true">↗</span></a><a href="https://github.com/Meenar-9196" target="_blank" rel="noopener noreferrer" className="button button-outline">GitHub <span aria-hidden="true">↗</span></a></div></div></section>
    </main><footer className="site-footer wrap"><span>© {new Date().getFullYear()} Meena Raja</span><span>DATA → CLARITY → ACTION</span><a href="#top">Back to top ↑</a></footer>
  </>;
}
